<!DOCTYPE html>
<html>
<head>
    <title>웹서버 week7</title>
    ** catch **
</head>
<body>
    <script>
        let promise = new Promise((resolve, reject) => {
            setTimeout(() => reject(new Error("에러 발생!")), 1000);
        });

        // .catch(f)는 promise.then(null, f)과 동일하게 작동합니다
        promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
    </script>
</body>
</html>